apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: ziad
type: Opaque
stringData:
  JWT_SECRET: "CHANGE_ME_very_long_secret_at_least_32_chars"
  JWT_EXP_MINUTES: "120"
  ADMIN_DEFAULT_PASSWORD: "yIG8wsTGE9wLcAdipSFO"