apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiemlhZGFsYWpsb3VuaSIsInBhc3N3b3JkIjoiZ2hwX1pFcFhmazQxczFWOHE4aWphZklnOTZzeHM0c2hBRDRFT0NhTSIsImF1dGgiOiJlbWxoWkdGc1lXcHNiM1Z1YVRwbmFIQmZXa1Z3V0dack5ERnpNVlk0Y1RocGFtRm1TV2M1Tm5ONGN6UnphRUZFTkVWUFEyRk4ifX19
kind: Secret
metadata:
  name: image-pull-secret
  namespace: ziad
type: kubernetes.io/dockerconfigjson
