backend:
  replicas: 3
  imagePullSecrets: image-pull-secret
  repository:
    image: ghcr.io/ziadalajlouni/backend
    tag: "v1"
frontend:
  repository:
    image: ghcr.io/ziadalajlouni/infra-x/frontend
    tag: "latest"